### ISSUE TITLE
Search as you type

### ISSUE THREAD

**Issue by OliverDimitrov** [polydice/ICInputAccessory#10]
Hi there, me again :)

Is it possible to add delegate method that will return on each keystroke? I need this since I need to perform search for available tags before adding one.

Thanks.

**Comment by bcylin** [comment]
Yes, it's possible to achieve that. I'll look into it after releasing `1.3.0`. Thanks again for the feedback.

**Comment by OliverDimitrov** [comment]
If I may ask, when is this happening? :)

**Comment by bcylin** [comment]
New delegate method can be found on the `develop` branch:

```swift
@objc optional func tokenField(_ tokenField: ICTokenField, didChangeInputText text: String)
```
