### ISSUE TITLE
Hiding delimiterLabel

### ISSUE THREAD

**Issue by woogii** [polydice/ICInputAccessory#11]
Hi, there.
Thanks for your project.
I am about to use your team's project in my application and having one question.
Is there any way that I can hide delimiterLabel property in ICToken class?

**Comment by bcylin** [comment]
Yes, one possible way is to have a customized delimiter, and layout `ICToken` based on it. It should have zero width when set with an empty string. Thanks for the idea. I'll take a look at it. Feedback and pull requests are always welcome.

**Comment by bcylin** [comment]
Added a delegate method. Returning an empty string should hide the delimiter.

```swift
func tokenField(_ tokenField: ICTokenField, subsequentDelimiterForCompletedText text: String) -> String {
  return ""
}
```

**Comment by woogii** [comment]
Thanks, @bcylin. It works like a charm. :)

**Comment by woogii** [comment]
Thanks, @bcylin. It works like a charm. :)
