### ISSUE TITLE
IBDesignables errors 

### ISSUE THREAD

**Issue by woogii** [polydice/ICInputAccessory#12]
Hi, I have a question.
Every time I open my storyboard, I encounter this type of error.

>  Failed to render and update auto layout status for xxxViewController (gPu-Al-cGo): dlopen(ICInputAccessory.framework, 1): Symbol not found: __TMps13OptionSetType
>   Referenced from: ICInputAccessory.framework.....)

I haven't used any @IBDesignable designation in my code and declare the customized ICTokenField class which is the same as the code of the sample project. I am currently using Swift 2.3 and Xcode 8.1. Do you have any suggestion?

**Comment by bcylin** [comment]
I ran the example project with Xcode 8.1 on 10.12.2. I didn't have the issue when opening Example/Main.storyboard. You were using Swift 2.3 so I suppose it's `v1.2.0`. Did you install the library via CocoaPods?

**Comment by bcylin** [comment]
@woogii I think I found a way to reproduce this error.

In the identity inspector of interface builder, the custom class module should be set to `ICInputAccessory`. There'll be symbol not found error if it's left blank. Please try this out to see if it fixes the issue.

<img width="260" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2032500/21575835/0067fe5e-cf56-11e6-8c95-275eb87d3c84.png">

**Comment by woogii** [comment]
Thanks for your answers. Yes, I installed `ICInputAccessory` via Cocoapods. 
I can't set the custom class module in the storyboard file since I didn't lay out any view in storyboard related to ICInputAccessory. I am using ICInputAccessory  by writing code like below, which is the same as the code in the demo.

```
private let tokenField = CustomizedTokenField() 
navigationItem.titleView = tokenField
```

**Comment by bcylin** [comment]
Can you control click on your storyboard and **Open As** > **Source Code**, search for the text `customClass=` to see if any element is accidentally set to an `ICInputAccessory` class?

**Comment by woogii** [comment]
I can't find any element which is set to an `ICInputAccessory` in the source code.  It is quite strange because I can run my project on my device even though I have those errors. Thanks for your comments.

**Comment by bcylin** [comment]
It seems to have something to do with the pod target's scope after CocoaPods 1.0. Can you try this workaround? You might need to set the config based on the `target.name` so it won't affect other pods.

https://github.com/polydice/ICInputAccessory/commit/43cd12d70654f2698d3d027b189885cc546650de#diff-4a25b996826623c4a3a4910f47f10c30

**Comment by woogii** [comment]
The errors disappeared after migrating to Swift 3.0. Thanks.
