### ISSUE TITLE
The delegate do not know when characters are deleted

### ISSUE THREAD

**Issue by tapsandswipes** [polydice/ICInputAccessory#15]
If you start typing and then tap the delete button in the keyboard, the characters are deleted but the delegate do not receive the call to `tokenField(_,didChangeInputText:)`

**Comment by czars** [comment]
Thank for your report.
Currently, `textFieldShouldDelete` is not support `tokenField(_,didChangeInputText:)` yet.
We will figure out how to make `textFieldShouldDelete` to support `tokenField(_,didChangeInputText:)`

Thanks again
