### ISSUE TITLE
Framework built via Carthage contains Frameworks/libswiftCore.dylib and others

### ISSUE THREAD

**Issue by derpoliuk** [polydice/ICInputAccessory#31]
This results in failure to upload archive to App Store Connect. Manually deleting `ICInputAccessory.framework/Frameworks` folder fixes the problem, but it's not a sustainable solution.

Screenshot of Finder:

<img width="1238" alt="screen shot 2019-02-12 at 2 29 02 pm" src="https://user-images.githubusercontent.com/1434418/52635525-c6831500-2ed2-11e9-8db6-c87d3c0ead0a.png">

**Comment by bcylin** [comment]
Hi @derpoliuk, thanks for reporting this issue. There will soon be a fix.

Can you try a `Cartfile` with the following specification and see if it works for you?

```
github "bcylin/ICInputAccessory" "feature/fix-embedded-library-issue"
```

**Comment by derpoliuk** [comment]
@bcylin thank you for getting back to me.

> Can you try a `Cartfile` with the following specification and see if it works for you?

It worked for me, thanks!

**Comment by bcylin** [comment]
@dlackty is it time to merge #32 and create `release/2.0.1` if it looks all right?

**Comment by dlackty** [comment]
@bcylin Sure let's do this.

**Comment by derpoliuk** [comment]
@bcylin, @dlackty thank you for update!
