### ISSUE TITLE
Empty string is registered as token

### ISSUE THREAD

**Issue by OliverDimitrov** [polydice/ICInputAccessory#9]
Hi! 
I'm trying to use your component and I'm pretty much satisfied from it, but I've hit a rock when I'm pressing just space. It keeps adding tokens, which are pretty much in every case invalid. 

I've tried using something like this in didEnterText delegate method: 
var tokens = tagsTextField.texts
tokens.removeLast()
tagsTextField.resetTokens()
for token in tokens {
    tagsTextField.textField.text = token
    tagsTextField.completeCurrentInputText()
}
but this redraws all tags and I don't like that jump all the time. 

Can you either remove the empty string as valid token or provide us a way to check the text before adding as a token.
Or probably best would be to add an array of invalid strings.

Using the develop branch (Swift 3.0 version) with Cocoapods
pod 'ICInputAccessory/TokenField', :git => 'https://github.com/polydice/ICInputAccessory.git' , :branch => 'develop'

Thanks.

**Comment by bcylin** [comment]
Adding a delegate method to check if the input text is valid could be one of the approaches. I'll look into it. Thanks for the feedback.

**Comment by OliverDimitrov** [comment]
Are you planning on supporting that soon or should I look for another alternative ?
Thanks.
